Repository XxThunderBlastxX/chamting-app, pull requests merged in 2023-03, with the labels that each got.

#28 Buttons changed
  lib/src/features/authentication/presentation/login/login.dart
  lib/src/features/authentication/presentation/signup/sign_up.dart
  lib/src/features/onboarding/onboarding.dart
  pubspec.lock
Labels: good first issue, Easy, JWOC

#30 Solves issue Build a user model #29
  build.yaml
  lib/main.dart
  lib/src/app/constants/assets.gen.dart
  lib/src/app/fonts/big_fonts.dart
  lib/src/app/theme/theme.dart
  lib/src/features/authentication/domain/user_model.dart
  lib/src/providers/global_providers.dart
  lib/src/providers/user_provider.dart
  pubspec.lock
  pubspec.yaml
Labels: Medium, JWOC

#46 Continuously check for internet connectivity and provide stream for connectivity #45 solved under JWOC
  lib/common/network_widget.dart
  lib/common/styled_button.dart
  lib/common/textfield_widgets.dart
  lib/src/app/constants/enums.dart
  lib/src/features/authentication/presentation/login/login_screen.dart
  lib/src/features/authentication/presentation/signup/sign_up_screen.dart
  lib/src/features/home/presentation/home.dart
  lib/src/features/onboarding/onboarding.dart
  lib/src/providers/connectivity_provider.dart
  lib/src/providers/global_providers.dart
  pubspec.lock
  pubspec.yaml
Labels: Hard, JWOC

#50 Design chat UI page in Figma #48
  ui/sagnik-sanyal-chat_ui.png
Labels: Medium, JWOC

#52 Add linting to project for better code practice #51
  analysis_options.yaml
  lib/common/network_widget.dart
  lib/common/textfield_widgets.dart
  lib/main.dart
  lib/src/app.dart
  lib/src/app/errors/failure.dart
  lib/src/app/theme/colors.dart
  lib/src/features/authentication/app/login_notifier.dart
  lib/src/features/authentication/app/signup_notifier.dart
  lib/src/features/authentication/data/auth_repository.dart
  lib/src/features/authentication/domain/states/login_state.dart
  lib/src/features/authentication/domain/states/sign_up_state.dart
  lib/src/features/authentication/presentation/login/login_screen.dart
  lib/src/features/authentication/presentation/signup/sign_up_screen.dart
  lib/src/features/home/presentation/home.dart
  lib/src/features/onboarding/onboarding.dart
  lib/src/providers/connectivity_provider.dart
  lib/src/providers/global_providers.dart
  lib/src/providers/local_storage_provider.dart
  lib/src/providers/user_provider.dart
  lib/src/utils/windows_button.dart
  pubspec.yaml
Labels: Hard, JWOC
